site_name: PolyGlot
theme: readthedocs
nav:
  - index.md
  - Android:
    - android/index.md
    - android/properties.md
    - android/lexicon.md
    - android/lexeme-utilities.md
    - android/pos.md
    - android/pos-inflections.md    
    - android/inflection-auto-generation.md    